// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/unit/discovery_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app/models/control_command/blink_command.dart' as _i7;
import 'package:app/models/control_command/fade_command.dart' as _i6;
import 'package:app/models/control_command/set_command.dart' as _i5;
import 'package:app/models/control_command/strobe_command.dart' as _i8;
import 'package:app/models/pwm_controller.dart' as _i4;
import 'package:app/repositories/device_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeviceScanState_0 extends _i1.SmartFake
    implements _i2.DeviceScanState {
  _FakeDeviceScanState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeviceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceRepository extends _i1.Mock implements _i2.DeviceRepository {
  MockDeviceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceScanState get currentScanState =>
      (super.noSuchMethod(
            Invocation.getter(#currentScanState),
            returnValue: _FakeDeviceScanState_0(
              this,
              Invocation.getter(#currentScanState),
            ),
          )
          as _i2.DeviceScanState);

  @override
  _i3.Stream<_i2.DeviceScanState> get scanState =>
      (super.noSuchMethod(
            Invocation.getter(#scanState),
            returnValue: _i3.Stream<_i2.DeviceScanState>.empty(),
          )
          as _i3.Stream<_i2.DeviceScanState>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  Map<String, dynamic> get connectionHealth =>
      (super.noSuchMethod(
            Invocation.getter(#connectionHealth),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<List<_i4.PWMController>> scanForDevices({Duration? timeout}) =>
      (super.noSuchMethod(
            Invocation.method(#scanForDevices, [], {#timeout: timeout}),
            returnValue: _i3.Future<List<_i4.PWMController>>.value(
              <_i4.PWMController>[],
            ),
          )
          as _i3.Future<List<_i4.PWMController>>);

  @override
  _i3.Future<Set<String>> scanForControllerIds(
    Iterable<String>? controllerIds, {
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #scanForControllerIds,
              [controllerIds],
              {#timeout: timeout},
            ),
            returnValue: _i3.Future<Set<String>>.value(<String>{}),
          )
          as _i3.Future<Set<String>>);

  @override
  _i3.Future<void> connect(String? controllerId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [controllerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<int>> readChannelStates() =>
      (super.noSuchMethod(
            Invocation.method(#readChannelStates, []),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);

  @override
  _i3.Future<void> sendSetCommand(_i5.SetCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendSetCommand, [command]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendFadeCommand(_i6.FadeCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendFadeCommand, [command]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendBlinkCommand(_i7.BlinkCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendBlinkCommand, [command]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendStrobeCommand(_i8.StrobeCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendStrobeCommand, [command]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
