// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/unit/orchestration_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/models/orchestration/execution_log_entry.dart' as _i5;
import 'package:app/models/orchestration/toggle_scene.dart' as _i2;
import 'package:app/repositories/orchestration_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeToggleScene_0 extends _i1.SmartFake implements _i2.ToggleScene {
  _FakeToggleScene_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrchestrationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrchestrationRepository extends _i1.Mock
    implements _i3.OrchestrationRepository {
  MockOrchestrationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ToggleScene>> loadScenes() =>
      (super.noSuchMethod(
            Invocation.method(#loadScenes, []),
            returnValue: _i4.Future<List<_i2.ToggleScene>>.value(
              <_i2.ToggleScene>[],
            ),
          )
          as _i4.Future<List<_i2.ToggleScene>>);

  @override
  _i4.Future<_i2.ToggleScene> upsertScene(_i2.ToggleScene? scene) =>
      (super.noSuchMethod(
            Invocation.method(#upsertScene, [scene]),
            returnValue: _i4.Future<_i2.ToggleScene>.value(
              _FakeToggleScene_0(
                this,
                Invocation.method(#upsertScene, [scene]),
              ),
            ),
          )
          as _i4.Future<_i2.ToggleScene>);

  @override
  _i4.Future<void> deleteScene(String? sceneId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteScene, [sceneId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ExecutionLogEntry>> loadExecutionLogs() =>
      (super.noSuchMethod(
            Invocation.method(#loadExecutionLogs, []),
            returnValue: _i4.Future<List<_i5.ExecutionLogEntry>>.value(
              <_i5.ExecutionLogEntry>[],
            ),
          )
          as _i4.Future<List<_i5.ExecutionLogEntry>>);

  @override
  _i4.Future<void> appendExecutionLog(_i5.ExecutionLogEntry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#appendExecutionLog, [entry]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearExecutionLogs() =>
      (super.noSuchMethod(
            Invocation.method(#clearExecutionLogs, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
