// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/unit/power_management_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:app/models/control_command/blink_command.dart' as _i9;
import 'package:app/models/control_command/fade_command.dart' as _i8;
import 'package:app/models/control_command/set_command.dart' as _i7;
import 'package:app/models/control_command/strobe_command.dart' as _i10;
import 'package:app/models/monitoring_data.dart' as _i2;
import 'package:app/models/power_management.dart' as _i3;
import 'package:app/models/pwm_controller.dart' as _i6;
import 'package:app/services/ble_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMonitoringData_0 extends _i1.SmartFake
    implements _i2.MonitoringData {
  _FakeMonitoringData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePowerManagementConfig_1 extends _i1.SmartFake
    implements _i3.PowerManagementConfig {
  _FakePowerManagementConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BLEService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBLEService extends _i1.Mock implements _i4.BLEService {
  MockBLEService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i5.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i6.PWMController>> scanForDevices({int? timeout = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#scanForDevices, [], {#timeout: timeout}),
            returnValue: _i5.Future<List<_i6.PWMController>>.value(
              <_i6.PWMController>[],
            ),
          )
          as _i5.Future<List<_i6.PWMController>>);

  @override
  _i5.Future<void> connect(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [deviceId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Set<String>> scanForControllerIds(
    Iterable<String>? controllerIds, {
    Duration? timeout = const Duration(seconds: 5),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #scanForControllerIds,
              [controllerIds],
              {#timeout: timeout},
            ),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Future<List<int>> readChannelStates() =>
      (super.noSuchMethod(
            Invocation.method(#readChannelStates, []),
            returnValue: _i5.Future<List<int>>.value(<int>[]),
          )
          as _i5.Future<List<int>>);

  @override
  _i5.Future<_i2.MonitoringData> readTelemetrySnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#readTelemetrySnapshot, []),
            returnValue: _i5.Future<_i2.MonitoringData>.value(
              _FakeMonitoringData_0(
                this,
                Invocation.method(#readTelemetrySnapshot, []),
              ),
            ),
          )
          as _i5.Future<_i2.MonitoringData>);

  @override
  _i5.Future<_i5.Stream<_i2.MonitoringData>> enableTelemetryNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#enableTelemetryNotifications, []),
            returnValue: _i5.Future<_i5.Stream<_i2.MonitoringData>>.value(
              _i5.Stream<_i2.MonitoringData>.empty(),
            ),
          )
          as _i5.Future<_i5.Stream<_i2.MonitoringData>>);

  @override
  _i5.Future<void> disableTelemetryNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#disableTelemetryNotifications, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendTelemetryCommand({
    required int? commandId,
    required int? parameter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendTelemetryCommand, [], {
              #commandId: commandId,
              #parameter: parameter,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendSetCommand(_i7.SetCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendSetCommand, [command]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendFadeCommand(_i8.FadeCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendFadeCommand, [command]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendBlinkCommand(_i9.BlinkCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendBlinkCommand, [command]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendStrobeCommand(_i10.StrobeCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendStrobeCommand, [command]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, dynamic> getConnectionHealthInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionHealthInfo, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<_i3.PowerManagementConfig> readPowerManagementConfig() =>
      (super.noSuchMethod(
            Invocation.method(#readPowerManagementConfig, []),
            returnValue: _i5.Future<_i3.PowerManagementConfig>.value(
              _FakePowerManagementConfig_1(
                this,
                Invocation.method(#readPowerManagementConfig, []),
              ),
            ),
          )
          as _i5.Future<_i3.PowerManagementConfig>);

  @override
  _i5.Future<void> sendPowerCommand(_i3.PowerCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendPowerCommand, [command]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.MonitoringData> readMonitoringData() =>
      (super.noSuchMethod(
            Invocation.method(#readMonitoringData, []),
            returnValue: _i5.Future<_i2.MonitoringData>.value(
              _FakeMonitoringData_0(
                this,
                Invocation.method(#readMonitoringData, []),
              ),
            ),
          )
          as _i5.Future<_i2.MonitoringData>);

  @override
  _i5.Future<_i5.Stream<_i2.MonitoringData>> enableMonitoringNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#enableMonitoringNotifications, []),
            returnValue: _i5.Future<_i5.Stream<_i2.MonitoringData>>.value(
              _i5.Stream<_i2.MonitoringData>.empty(),
            ),
          )
          as _i5.Future<_i5.Stream<_i2.MonitoringData>>);

  @override
  _i5.Future<void> disableMonitoringNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#disableMonitoringNotifications, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i5.Stream<List<int>>> enableChannelStateNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#enableChannelStateNotifications, []),
            returnValue: _i5.Future<_i5.Stream<List<int>>>.value(
              _i5.Stream<List<int>>.empty(),
            ),
          )
          as _i5.Future<_i5.Stream<List<int>>>);

  @override
  _i5.Future<void> disableChannelStateNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#disableChannelStateNotifications, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i5.Stream<List<int>>> enableFontStatusNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#enableFontStatusNotifications, []),
            returnValue: _i5.Future<_i5.Stream<List<int>>>.value(
              _i5.Stream<List<int>>.empty(),
            ),
          )
          as _i5.Future<_i5.Stream<List<int>>>);

  @override
  _i5.Future<void> disableFontStatusNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#disableFontStatusNotifications, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
