// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/unit/power_management_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/models/power_management.dart' as _i2;
import 'package:app/repositories/power_management_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePowerManagementConfig_0 extends _i1.SmartFake
    implements _i2.PowerManagementConfig {
  _FakePowerManagementConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PowerManagementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPowerManagementRepository extends _i1.Mock
    implements _i3.PowerManagementRepository {
  MockPowerManagementRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PowerManagementConfig> readConfig() =>
      (super.noSuchMethod(
            Invocation.method(#readConfig, []),
            returnValue: _i4.Future<_i2.PowerManagementConfig>.value(
              _FakePowerManagementConfig_0(
                this,
                Invocation.method(#readConfig, []),
              ),
            ),
          )
          as _i4.Future<_i2.PowerManagementConfig>);

  @override
  _i4.Future<void> sendCommand(_i2.PowerCommand? command) =>
      (super.noSuchMethod(
            Invocation.method(#sendCommand, [command]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setHighTemperatureThreshold(double? temperatureCelsius) =>
      (super.noSuchMethod(
            Invocation.method(#setHighTemperatureThreshold, [
              temperatureCelsius,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setRecoveryThreshold(double? temperatureCelsius) =>
      (super.noSuchMethod(
            Invocation.method(#setRecoveryThreshold, [temperatureCelsius]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSleepVoltageThreshold(double? voltage) =>
      (super.noSuchMethod(
            Invocation.method(#setSleepVoltageThreshold, [voltage]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setWakeVoltageThreshold(double? voltage) =>
      (super.noSuchMethod(
            Invocation.method(#setWakeVoltageThreshold, [voltage]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> forceSleep() =>
      (super.noSuchMethod(
            Invocation.method(#forceSleep, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> forceWake() =>
      (super.noSuchMethod(
            Invocation.method(#forceWake, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
