// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/unit/saved_controller_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/models/saved_controller.dart' as _i2;
import 'package:app/repositories/saved_controller_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSavedController_0 extends _i1.SmartFake
    implements _i2.SavedController {
  _FakeSavedController_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SavedControllerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedControllerRepository extends _i1.Mock
    implements _i3.SavedControllerRepository {
  MockSavedControllerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i2.SavedController>> get controllersStream =>
      (super.noSuchMethod(
            Invocation.getter(#controllersStream),
            returnValue: _i4.Stream<List<_i2.SavedController>>.empty(),
          )
          as _i4.Stream<List<_i2.SavedController>>);

  @override
  List<_i2.SavedController> get currentControllers =>
      (super.noSuchMethod(
            Invocation.getter(#currentControllers),
            returnValue: <_i2.SavedController>[],
          )
          as List<_i2.SavedController>);

  @override
  _i4.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.SavedController>> loadSavedControllers() =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedControllers, []),
            returnValue: _i4.Future<List<_i2.SavedController>>.value(
              <_i2.SavedController>[],
            ),
          )
          as _i4.Future<List<_i2.SavedController>>);

  @override
  _i4.Future<_i2.SavedController> addSavedController(
    _i2.SavedController? controller,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addSavedController, [controller]),
            returnValue: _i4.Future<_i2.SavedController>.value(
              _FakeSavedController_0(
                this,
                Invocation.method(#addSavedController, [controller]),
              ),
            ),
          )
          as _i4.Future<_i2.SavedController>);

  @override
  _i4.Future<_i2.SavedController> renameSavedController(
    String? controllerId,
    String? alias,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renameSavedController, [controllerId, alias]),
            returnValue: _i4.Future<_i2.SavedController>.value(
              _FakeSavedController_0(
                this,
                Invocation.method(#renameSavedController, [
                  controllerId,
                  alias,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.SavedController>);

  @override
  _i4.Future<List<_i2.SavedController>> removeSavedController(
    String? controllerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeSavedController, [controllerId]),
            returnValue: _i4.Future<List<_i2.SavedController>>.value(
              <_i2.SavedController>[],
            ),
          )
          as _i4.Future<List<_i2.SavedController>>);

  @override
  _i4.Future<void> persistSavedControllers(
    List<_i2.SavedController>? controllers,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#persistSavedControllers, [controllers]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.SavedController?> findSavedController(String? controllerId) =>
      (super.noSuchMethod(
            Invocation.method(#findSavedController, [controllerId]),
            returnValue: _i4.Future<_i2.SavedController?>.value(),
          )
          as _i4.Future<_i2.SavedController?>);

  @override
  _i4.Future<void> clearSavedControllers() =>
      (super.noSuchMethod(
            Invocation.method(#clearSavedControllers, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
