// Mocks generated by Mockito 5.4.6 from annotations
// in app/test/unit/telemetry_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:app/models/monitoring_data.dart' as _i2;
import 'package:app/repositories/telemetry_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMonitoringData_0 extends _i1.SmartFake
    implements _i2.MonitoringData {
  _FakeMonitoringData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TelemetryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTelemetryRepository extends _i1.Mock
    implements _i3.TelemetryRepository {
  MockTelemetryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MonitoringData> readTelemetrySnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#readTelemetrySnapshot, []),
            returnValue: _i4.Future<_i2.MonitoringData>.value(
              _FakeMonitoringData_0(
                this,
                Invocation.method(#readTelemetrySnapshot, []),
              ),
            ),
          )
          as _i4.Future<_i2.MonitoringData>);

  @override
  _i4.Future<_i4.Stream<_i2.MonitoringData>> subscribeTelemetry() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeTelemetry, []),
            returnValue: _i4.Future<_i4.Stream<_i2.MonitoringData>>.value(
              _i4.Stream<_i2.MonitoringData>.empty(),
            ),
          )
          as _i4.Future<_i4.Stream<_i2.MonitoringData>>);

  @override
  _i4.Future<void> unsubscribeTelemetry() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeTelemetry, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.MonitoringData> readMonitoringData() =>
      (super.noSuchMethod(
            Invocation.method(#readMonitoringData, []),
            returnValue: _i4.Future<_i2.MonitoringData>.value(
              _FakeMonitoringData_0(
                this,
                Invocation.method(#readMonitoringData, []),
              ),
            ),
          )
          as _i4.Future<_i2.MonitoringData>);

  @override
  _i4.Future<_i4.Stream<_i2.MonitoringData>> subscribeMonitoring() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeMonitoring, []),
            returnValue: _i4.Future<_i4.Stream<_i2.MonitoringData>>.value(
              _i4.Stream<_i2.MonitoringData>.empty(),
            ),
          )
          as _i4.Future<_i4.Stream<_i2.MonitoringData>>);

  @override
  _i4.Future<void> unsubscribeMonitoring() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeMonitoring, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<int>> readChannelStates() =>
      (super.noSuchMethod(
            Invocation.method(#readChannelStates, []),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<_i4.Stream<List<int>>> subscribeChannelStates() =>
      (super.noSuchMethod(
            Invocation.method(#subscribeChannelStates, []),
            returnValue: _i4.Future<_i4.Stream<List<int>>>.value(
              _i4.Stream<List<int>>.empty(),
            ),
          )
          as _i4.Future<_i4.Stream<List<int>>>);

  @override
  _i4.Future<void> unsubscribeChannelStates() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeChannelStates, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
